name: Sync src & docs to deploy branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  TARGET_BRANCH: deploy

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout deploy branch
        run: |
          git fetch origin ${{ env.TARGET_BRANCH }}
          git checkout -B ${{ env.TARGET_BRANCH }} origin/${{ env.TARGET_BRANCH }}

      - name: Clean deploy branch
        run: |
          git rm -rf .
          rm -rf *

      - name: Pull src & docs from main
        run: |
          git checkout origin/main -- src docs

      - name: Flatten src into root
        run: |
          cp -R src/* .
          rm -rf src

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync src & docs from main"
            git push origin ${{ env.TARGET_BRANCH }}
          fi
