name: JSDoc Generation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  on-pr-merged:
    name: JSDoc
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Generate JSDoc
        run: npx jsdoc -c jsdoc.json
      - name: Commit and push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs
          git diff --cached --quiet || git commit -m "Update docs"
          git push origin develop
