name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - test-cipipeline
  pull_request:

jobs:
  lint-and-docs:
    name: Lint with ESLint and Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run Prettier
        run: npx prettier . --check

  validate-html:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Validate HTML files using W3C API
        run: |
          failed=0
          for file in ./*.html; do
            if [ -f "$file" ]; then
              echo "Validating $file"
              response=$(curl -s -H "Content-Type: text/html; charset=utf-8" --data-binary "@$file" "https://validator.w3.org/nu/?out=json")
              messages=$(echo "$response" | jq '.messages | length')
              if [ "$messages" -eq 0 ]; then
                echo "✅ $file is valid"
              else
                echo "❌ $file has $messages issue(s):"
                echo "$response" | jq -r '.messages[] | "- [\(.type)] \(.message) at line \(.lastLine // "unknown")"'
                failed=1
              fi
            fi
          done
          exit $failed

  tests:
    name: Unit Tests with Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run all unit tests with coverage
        run: npm run test:unit
      - name: Upload HTML Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov-report

  puppeteer-tests:
    name: Puppeteer E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run all E2E tests
        run: npm run test:e2e

  playwright-tests:
    name: Playwright Browser Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - uses: microsoft/playwright-github-action@v1
        with:
          runInstall: true
      - name: Run all browser tests
        run: npm run test:browser
